### ISSUE TITLE
gulp serve fails due to syntax error

### ISSUE THREAD

**Issue by heyitsols** [eruecco87/PokemonGoBot-RocketTheme#1]
I get the following when running `gulp serve`, after `npm install` and `bower install` have successfully completed. Output below:

```
$ gulp serve

/path/gulpfile.js:12
gulp.task('styles', () => {
                     ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
```

**Versions**

```
$ node --version
v0.10.42
$ gulp -v
[10:35:19] CLI version 3.9.1
[10:35:19] Local version 3.9.1
```

**Comment by eruecco87-zz** [comment]
You're running a really old version of node, the latest version of node is up to v6.3.1.

Please update your node version and try again.

**Comment by heyitsols** [comment]
Weird how CentOS 7 supplies such an out of date version of nodejs. Fixed though, thanks
